# Generated by Django 5.2.17 on 2026-09-13 13:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_no', models.CharField(max_length=20, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('role', models.CharField(choices=[('dispatcher', '调度员'), ('guard', '押运员'), ('driver', '驾驶员'), ('branch_clerk', '网点柜员'), ('vault_keeper', '金库管理员'), ('admin', '系统管理员')], default='guard', max_length=20, verbose_name='角色')),
                ('position', models.CharField(blank=True, choices=[('car_captain', '车长'), ('escort_guard', '武装押运员'), ('driver', '驾驶员'), ('dispatcher', '调度员'), ('vault_keeper', '金库管理员'), ('clerk', '网点柜员')], default='', max_length=20, verbose_name='岗位')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('id_card', models.CharField(blank=True, default='', max_length=18, verbose_name='身份证号')),
                ('active_duty', models.BooleanField(default=True, verbose_name='今日在岗')),
            ],
            options={
                'verbose_name': '用户/人员',
                'verbose_name_plural': '用户/人员',
                'ordering': ['employee_no'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
