# Generated by Django 5.2.17 on 2026-09-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('vacation', '休假'), ('training', '培训'), ('rest', '休息'), ('other', '其他')], default='', max_length=20, verbose_name='缺勤类型'),
        ),
    ]
