# Generated by Django 5.2.17 on 2026-09-13 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='网点编号')),
                ('name', models.CharField(max_length=100, verbose_name='网点名称')),
                ('short_name', models.CharField(blank=True, default='', max_length=50, verbose_name='简称')),
                ('branch_type', models.CharField(choices=[('head_vault', '中心金库'), ('sub_vault', '分金库'), ('branch', '营业网点'), ('self_bank', '自助银行')], default='branch', max_length=20, verbose_name='类型')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='地址')),
                ('contact_person', models.CharField(blank=True, default='', max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('service_start', models.TimeField(blank=True, null=True, verbose_name='营业开始')),
                ('service_end', models.TimeField(blank=True, null=True, verbose_name='营业结束')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '网点/金库',
                'verbose_name_plural': '网点/金库',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_no', models.CharField(max_length=30, unique=True, verbose_name='款箱编号')),
                ('box_type', models.CharField(choices=[('teller', '柜员尾箱'), ('cash', '现金箱'), ('voucher', '凭证箱'), ('atm', 'ATM加钞箱')], default='teller', max_length=20, verbose_name='箱型')),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='面额合计(元)')),
                ('status', models.CharField(choices=[('idle', '在库空闲'), ('in_transit', '在途'), ('delivered', '已送达')], default='idle', max_length=20, verbose_name='状态')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('owner_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='core.branch', verbose_name='归属网点')),
            ],
            options={
                'verbose_name': '款箱',
                'verbose_name_plural': '款箱',
                'ordering': ['box_no'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='线路编号')),
                ('name', models.CharField(max_length=100, verbose_name='线路名称')),
                ('distance_km', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='里程(公里)')),
                ('est_minutes', models.PositiveIntegerField(default=120, verbose_name='预计用时(分钟)')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_out', to='core.branch', verbose_name='出发金库')),
            ],
            options={
                'verbose_name': '押运线路',
                'verbose_name_plural': '押运线路',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(editable=False, max_length=30, unique=True, verbose_name='任务编号')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='任务名称')),
                ('direction', models.CharField(choices=[('outbound', '下解（金库→网点）'), ('inbound', '上收（网点→金库）')], default='outbound', max_length=10, verbose_name='方向')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('planned_depart', models.TimeField(blank=True, null=True, verbose_name='计划出发')),
                ('planned_return', models.TimeField(blank=True, null=True, verbose_name='计划返回')),
                ('actual_depart', models.DateTimeField(blank=True, null=True, verbose_name='实际出发')),
                ('actual_return', models.DateTimeField(blank=True, null=True, verbose_name='实际返回')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('planned', '已派车'), ('in_transit', '押运中'), ('abnormal', '异常挂起'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('notes', models.CharField(blank=True, default='', max_length=300, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depot_tasks', to='core.branch', verbose_name='金库')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.route', verbose_name='押运线路')),
            ],
            options={
                'verbose_name': '押运任务',
                'verbose_name_plural': '押运任务',
                'ordering': ['-planned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_task', models.CharField(choices=[('car_captain', '车长'), ('guard', '押运员'), ('driver', '驾驶员')], max_length=20, verbose_name='车上角色')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='人员')),
            ],
            options={
                'verbose_name': '任务人员安排',
                'unique_together': {('task', 'user')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(through='core.TaskAssignee', to=settings.AUTH_USER_MODEL, verbose_name='随车人员'),
        ),
        migrations.CreateModel(
            name='TaskBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_out', '待出库'), ('in_transit', '在途'), ('delivered', '已送达网点'), ('in_return', '返程在途'), ('returned', '已回收入库'), ('exception', '异常')], default='pending_out', max_length=20, verbose_name='流转状态')),
                ('seal_no', models.CharField(blank=True, default='', max_length=30, verbose_name='出库封签号')),
                ('exception_flag', models.BooleanField(default=False, verbose_name='存在异常')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cashbox', verbose_name='款箱')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
            options={
                'verbose_name': '任务款箱',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='boxes',
            field=models.ManyToManyField(through='core.TaskBox', to='core.cashbox', verbose_name='款箱'),
        ),
        migrations.CreateModel(
            name='TaskStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='顺序')),
                ('planned_arrival', models.DateTimeField(blank=True, null=True, verbose_name='计划到达')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='实际到达')),
                ('actual_departure', models.DateTimeField(blank=True, null=True, verbose_name='实际离开')),
                ('verify_code', models.CharField(blank=True, default='', max_length=6, verbose_name='交接验证码')),
                ('status', models.CharField(choices=[('pending', '待到达'), ('en_route', '前往中'), ('arrived', '已到达'), ('done', '交接完成'), ('skipped', '跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='停靠网点')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务停靠点',
                'ordering': ['sequence'],
                'unique_together': {('task', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40, verbose_name='事件代码')),
                ('message', models.CharField(max_length=300, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.task')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taskstop')),
            ],
            options={
                'verbose_name': '任务日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='taskbox',
            name='target_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_boxes', to='core.taskstop', verbose_name='目标/来源停靠点'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_no', models.CharField(editable=False, max_length=30, unique=True, verbose_name='异常编号')),
                ('category', models.CharField(choices=[('traffic', '交通延误'), ('seal', '封签异常'), ('box_damage', '款箱破损'), ('box_missing', '款箱短少'), ('personnel', '人员异常'), ('vehicle', '车辆故障'), ('weather', '天气原因'), ('security', '安全事件'), ('other', '其他')], max_length=20, verbose_name='异常类型')),
                ('severity', models.CharField(choices=[('low', '一般'), ('medium', '较重'), ('high', '严重')], default='low', max_length=10, verbose_name='严重程度')),
                ('description', models.TextField(verbose_name='情况描述')),
                ('status', models.CharField(choices=[('open', '待处理'), ('processing', '处理中'), ('resolved', '已处置')], default='open', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('resolution', models.TextField(blank=True, default='', verbose_name='处置说明')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处置时间')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL, verbose_name='处置人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.task', verbose_name='任务')),
                ('task_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taskbox', verbose_name='款箱')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taskstop', verbose_name='停靠点')),
            ],
            options={
                'verbose_name': '异常事件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('vault_out', '金库出库'), ('branch_recv', '网点接收'), ('branch_pickup', '网点移交'), ('vault_return', '金库回库')], max_length=20, verbose_name='交接阶段')),
                ('result', models.CharField(choices=[('confirmed', '核对一致'), ('seal_mismatch', '封签异常'), ('code_mismatch', '验证码不符'), ('box_missing', '款箱短少')], default='confirmed', max_length=20, verbose_name='核对结果')),
                ('seal_no_out', models.CharField(blank=True, default='', max_length=30, verbose_name='交出方封签号')),
                ('seal_no_in', models.CharField(blank=True, default='', max_length=30, verbose_name='接收方封签号')),
                ('seal_intact', models.BooleanField(default=True, verbose_name='封签完好')),
                ('code_verified', models.BooleanField(blank=True, null=True, verbose_name='验证码核验')),
                ('remark', models.CharField(blank=True, default='', max_length=300, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='交接时间')),
                ('from_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handovers_given', to=settings.AUTH_USER_MODEL, verbose_name='交出人')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_recorded', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handovers_received', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('task_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='core.taskbox', verbose_name='任务款箱')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taskstop', verbose_name='停靠点')),
            ],
            options={
                'verbose_name': '款箱交接记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='车牌号')),
                ('model', models.CharField(default='防弹运钞车', max_length=50, verbose_name='车型')),
                ('capacity', models.PositiveIntegerField(default=60, verbose_name='核载款箱数')),
                ('gps_device', models.CharField(blank=True, default='', max_length=30, verbose_name='GPS设备号')),
                ('status', models.CharField(choices=[('idle', '待命'), ('on_duty', '执行任务'), ('maintenance', '维修中')], default='idle', max_length=20, verbose_name='状态')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('home_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.branch', verbose_name='驻停金库')),
            ],
            options={
                'verbose_name': '押运车辆',
                'verbose_name_plural': '押运车辆',
                'ordering': ['plate'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.vehicle', verbose_name='押运车辆'),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='顺序')),
                ('planned_arrival', models.TimeField(blank=True, null=True, verbose_name='计划到达时间')),
                ('dwell_minutes', models.PositiveIntegerField(default=15, verbose_name='停留(分钟)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='core.branch', verbose_name='停靠网点')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.route', verbose_name='线路')),
            ],
            options={
                'verbose_name': '线路停靠点',
                'verbose_name_plural': '线路停靠点',
                'ordering': ['sequence'],
                'unique_together': {('route', 'sequence')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='taskbox',
            unique_together={('task', 'box')},
        ),
    ]
