# Generated by Django 5.2.17 on 2026-09-13 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handover',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='core.taskstop', verbose_name='停靠点'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.taskstop', verbose_name='停靠点'),
        ),
    ]
