# Generated by Django 5.2.17 on 2026-09-13 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_handover_stop_alter_incident_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbox',
            name='target_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_boxes', to='core.taskstop', verbose_name='目标/来源停靠点'),
        ),
    ]
