# Generated by Django 5.2.17 on 2026-09-13 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_taskbox_target_stop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_duty', models.BooleanField(verbose_name='变更后在岗')),
                ('leave_type', models.CharField(blank=True, default='', max_length=20, verbose_name='缺勤类型')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='事由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task', verbose_name='关联任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_logs', to=settings.AUTH_USER_MODEL, verbose_name='人员')),
            ],
            options={
                'verbose_name': '人员状态变更记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('idle', '待命'), ('on_duty', '执行任务'), ('maintenance', '维修中')], max_length=20, verbose_name='新状态')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='事由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task', verbose_name='关联任务')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='core.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '车辆状态变更记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
